# Generated by Django 3.0.3 on 2020-09-07 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('text_of_the_lesson', models.TextField()),
                ('level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SentencesToLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Lessons')),
                ('sentence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sentences')),
            ],
        ),
        migrations.AddField(
            model_name='lessons',
            name='sentences',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SentencesToLesson'),
        ),
    ]
