# Generated by Django 3.0.3 on 2020-09-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200907_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentences',
            name='predicate',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentences',
            name='subjective',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
